version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "5514:514"
    volumes:
      - .:/app
    environment:
      - ENV_VAR=example